# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SOAP-Data-Builder
version:      0.9
version_from: lib/SOAP/Data/Builder.pm
installdirs:  site
requires:
    SOAP::Lite:                    0.65

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
